### ISSUE TITLE
Autenticação de setor

### ISSUE THREAD

**Issue by LeoDevMeli** [netto-meli/w4g9-projeto-final#9]
CENÁRIO 1: O produto de um vendedor é registrado.
DESDE o produto de um Vendedor é registrado
E que o armazém é válido
E que o representante pertence ao armazém
E que o setor é válido
E que o setor corresponde ao tipo de produto
E que o setor tenha espaço disponível
QUANDO o representante entra no lote
ENTÃO o registro de compra é criado
E o lote é atribuído a um setor
E o representante é associado ao registro de estoque

**Comment by netto-meli** [comment]
autenticaçao JWT ?
